### PR TITLE
fix: add user secret key when using saved secrets

### PR DESCRIPTION
**Pull request by olevski**
/deploy renku=feat-jupyter-free-sessions amalthea-sessions=main renku-ui=andrea/jupyter-free-build renku-gateway=master extra-values=amalthea-sessions.deployCrd=false

### CODE REVIEW

**Comment by olevski** [comment]
This change is part of the following stack:

- #519 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

**Comment by leafty** [comment]
Note: for user secrets, we inject the data service API URL along with the user's Renku token to decrypt the secrets and not the cipher key directly. Should this approach be used for data connector secrets as well?

**Review by m-alisafaee — APPROVED** [review]
Thanks Tasko!

**Comment by olevski** [comment]
> Note: for user secrets, we inject the data service API URL along with the user's Renku token to decrypt the secrets and not the cipher key directly. Should this approach be used for data connector secrets as well?

> The init user secrets container then grabs the key from the internal API endpoint.

@leafty for the data connectors I followed the same thing we do right now in the renku repo. There we add the the decryption key in the secret that contains the configuration. And the csi rclone finishes the decryption of the saved secret.

We cannot use an init container because the pod cannot start at all (including the init containers) until the volumes are mounted. And the volume (i.e. data connector) cannot be mounted until rclone has the fully decrypted secret in order to do the mounting. So we cannot use an init container to decrypt the data connector secrets.

**Pull request merged**
