### PR TITLE
fix: add default value for secret kind when creating secrets

### PR DESCRIPTION
**Pull request by olevski**
This was causing a breaking change in the API. With the default the new API can be used without needing changes on the UI side.

/deploy renku=build/incidents-maintenance

### CODE REVIEW

**Comment by leafty** [comment]
@olevski Thanks

Note: Will re-deploy with `renku=build/incidents-maintenance` to check if the secrets UI is fixed.

**Review by leafty — CHANGES_REQUESTED** [review]
Now on secret creation, we get:

```
[2024-07-25 09:48:59 +0000] [111] [ERROR] Exception occurred while handling uri: 'https://renku-ci-ds-322.dev.renku.ch/api/data/user/secrets'
Traceback (most recent call last):
  File "handle_request", line 102, in handle_request
    try:
         
  File "/app/env/lib/python3.12/site-packages/renku_data_services/base_api/auth.py", line 39, in decorated_function
    response = await f(request, user, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/env/lib/python3.12/site-packages/renku_data_services/base_api/auth.py", line 150, in decorated_function
    response = await f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/env/lib/python3.12/site-packages/sanic_ext/extras/validation/decorator.py", line 75, in decorated_function
    retval = await retval
             ^^^^^^^^^^^^
  File "/app/env/lib/python3.12/site-packages/renku_data_services/users/blueprints.py", line 208, in _post
    kind=SecretKind[body.kind.value],
                    ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'value'
```

**Review by leafty — DISMISSED** [review]
LGTM, thanks

Note: See this for a potential schemathesis quick fix -> https://github.com/SwissDataScienceCenter/renku-data-services/issues/324#issuecomment-2250538517

**Comment by olevski** [comment]
Thanks @leafty. I just added your suggestion from that issue here. I did not want to merge this PR with the CI checks partially failing.

If this all passes and you are happy with the change please just merge this since I wont be around tomorrow.

**Review by leafty — APPROVED** [review]
LGTM

**Pull request merged**
