### PR TITLE
refactor: change all serial id columns to be GENERATED AS IDENTITY ones

### PR DESCRIPTION
**Pull request by Panaetius**
/deploy

### CODE REVIEW

**Comment by Panaetius** [comment]
This change is part of the following stack:

- #461 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

**Review by olevski — CHANGES_REQUESTED** [review]
This looks great Ralf. As discussed though lets add the locks for each table just to be safe. Thanks for finding the proper fix for this.

**Review by olevski — APPROVED** [review]

**Review by olevski — APPROVED** [review]

**Comment by leafty** [comment]
Can we make sure this works on an already-populated deployment? Make a test PR in `renku`, deploy prior to this migration, then add some data (e.g. add a resource class), then migrate and check that items can still be created.

**Comment by Panaetius** [comment]
I did that in the original PR before splitting off this change and locally, but just did it again in https://github.com/SwissDataScienceCenter/renku/pull/3820 to double check (Adding projects with repositories) and it works fine.

**Pull request merged**
