### PR TITLE
fix: tolerations. affinities and permissions

### PR DESCRIPTION
**Pull request by olevski**
Fixes two major issues:
- enforcement of the `no_default_access` flag on users
- resource classes getting copied/deserialized with the tolerations and affinities getting removed in the process

It also adds a few extra tests to check the enforcement of the `no_default_access` flag for users.

/deploy renku-data-services=fix-tolerations renku-notebooks=fix-tolerations

### CODE REVIEW

**Comment by rokroskar** [comment]
Thanks @olevski I tried this out - can confirm that the patch for restricting access to the default pool works as expected. 

I'm still having trouble with tolerations and affinities. I can set tolerations on pool creation (and they get properly stored), but the `PATCH /resource_pools/<id>/classes/<id>` fails with 

```
data-service [2023-11-02 21:39:31 +0000] [17] [ERROR] An unknown or unhandled exception occurred
data-service Traceback (most recent call last):
data-service   File "handle_request", line 97, in handle_request
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/base_api/auth.py", line 25, in decorated_function
data-service     response = await f(request, *args, **kwargs, user=user)
data-service                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/base_api/auth.py", line 44, in decorated_function
data-service     response = await f(request, *args, **kwargs, user=user)
data-service                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/sanic_ext/extras/validation/decorator.py", line 74, in decorated_function
data-service     retval = await retval
data-service              ^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/crc/blueprints.py", line 316, in _patch
data-service     return await self._put_patch(user, resource_pool_id, class_id, body)
data-service            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/crc/blueprints.py", line 327, in _put_patch
data-service     cls = await self.repo.update_resource_class(
data-service           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/crc/db.py", line 131, in decorated_function
data-service     response = await f(self, *args, **kwargs)
data-service                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/crc/db.py", line 447, in update_resource_class
data-service     setattr(cls, k, v)
data-service   File "/app/env/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 537, in __set__
data-service     self.impl.set(
data-service   File "/app/env/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1989, in set
data-service     collections.bulk_replace(
data-service   File "/app/env/lib/python3.11/site-packages/sqlalchemy/orm/collections.py", line 803, in bulk_replace
data-service     appender(member, _sa_initiator=initiator)
data-service   File "/app/env/lib/python3.11/site-packages/sqlalchemy/orm/collections.py", line 1130, in append
data-service     item = __set(self, item, _sa_initiator, NO_KEY)
data-service            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/sqlalchemy/orm/collections.py", line 1095, in __set
data-service     item = executor.fire_append_event(item, _sa_initiator, key=key)
data-service            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/sqlalchemy/orm/collections.py", line 687, in fire_append_event
data-service     return self.attr.fire_append_event(
data-service            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1756, in fire_append_event
data-service     value = fn(state, value, initiator or self._append_token, key=key)
data-service             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 63, in append
data-service     item_state = attributes.instance_state(item)
data-service                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service AttributeError: 'str' object has no attribute '_sa_instance_state'
```

I get another error on pool creation with `node_affinities`:

```
data-service [2023-11-02 22:20:42 +0000] [17] [ERROR] An unknown or unhandled exception occurred
data-service Traceback (most recent call last):
data-service   File "handle_request", line 97, in handle_request
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/base_api/auth.py", line 25, in decorated_function
data-service     response = await f(request, *args, **kwargs, user=user)
data-service                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/base_api/auth.py", line 44, in decorated_function
data-service     response = await f(request, *args, **kwargs, user=user)
data-service                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/sanic_ext/extras/validation/decorator.py", line 74, in decorated_function
data-service     retval = await retval
data-service              ^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/crc/blueprints.py", line 47, in _post
data-service     rp = models.ResourcePool.from_dict(body.model_dump(exclude_none=True))
data-service          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/crc/models.py", line 228, in from_dict
data-service     classes = [ResourceClass.from_dict(c) if isinstance(c, dict) else c for c in data["classes"]]
data-service               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/crc/models.py", line 228, in <listcomp>
data-service     classes = [ResourceClass.from_dict(c) if isinstance(c, dict) else c for c in data["classes"]]
data-service                ^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/crc/models.py", line 111, in from_dict
data-service     data["node_affinities"] = [
data-service                               ^
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/crc/models.py", line 112, in <listcomp>
data-service     NodeAffinity.from_dict(affinity) if isinstance(affinity, dict) else affinity
data-service     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.11/site-packages/renku_data_services/crc/models.py", line 75, in from_dict
data-service     return cls(**data)
data-service            ^^^^^^^^^^^
data-service TypeError: NodeAffinity.__init__() got an unexpected keyword argument 'requiredDuringScheduling'
data-service [2023-11-02 22:20:42 +0000] [17] [ERROR] An unknown or unhandled exception of type TypeError occurred
```

**Comment by olevski** [comment]
Oh and one more thing I need to remove the protections against patching/editing the resource classes that we put in at some time. That should be easy to do.

**Comment by olevski** [comment]
@rokroskar this is ready now, if you approve I can merge and do another bugfix release

**Review by rokroskar — APPROVED** [review]
Thanks @olevski! Tested the resource pool creation with tolerations + affinities: classes get created and the tolerations/affinities propagate properly to the resulting resources. 👍

**Review by mohammad-alisafaee — APPROVED** [review]

**Pull request merged**
